ame: "TODO to Issues"
description: "Create issues from TODO.md"
inputs:
  TOKEN: # github token
    description: "Github repo token"
    required: true
  PATH: # path of todo
    description: "Path to TODO file"
    required: true
    default: "./TODO.md"
outputs:
  issues: # number of issues created
    description: "The number of issues created"
runs:
  using: "node14"
  main: "index.js"
