name: 'TODO-Issues'
description: 'Create issues from TODO'
inputs:
  repo-token:
    description: 'Github repo token'
    required: true
  path:
    description: 'Path to TODO file'
    required: true
    default: './TODO'
outputs:
  issues:
    description: 'The number of issues created'
runs:
  using: 'node12'
  main: 'index.js'
