ame: "TODO-Issues"
description: "Create issues from TODO.md"
inputs:
  repo-token: # github token
    description: "Github repo token"
    required: true
  path: # path of to
    description: "Path to TODO file"
    required: true
    default: "./TODO.md"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node14"
  main: "index.js"
